const images = {
  one: require("./images/1.jpg").default,
  two: require("./images/2.jpg").default,
  three: require("./images/3.jpg").default,
  four: require("./images/4.jpg").default,
  five: require("./images/5.jpg").default,
  six: require("./images/6.jpg").default,
  seven: require("./images/7.jpg").default,
  eight: require("./images/8.jpg").default,
  nine: require("./images/9.jpg").default,
  ten: require("./images/10.jpg").default,
  eleven: require("./images/11.jpg").default,
  twelve: require("./images/12.jpg").default,
  thirteen: require("./images/13.jpg").default,
  fourteen: require("./images/14.jpg").default,
  fifteen: require("./images/15.jpg").default,
  sixteen: require("./images/16.jpg").default,
  seventeen: require("./images/17.jpg").default,
  eighteen: require("./images/18.jpg").default,
  nineteen: require("./images/19.jpg").default,
  twenty: require("./images/20.jpg").default,
  twentyone: require("./images/21.jpg").default,
  twentytwo: require("./images/22.jpg").default,
  twentythree: require("./images/23.jpg").default,
  twentyfour: require("./images/24.jpg").default,
  twentyfive: require("./images/25.jpg").default,
  twentysix: require("./images/26.jpg").default,
  twentyseven: require("./images/27.jpg").default,
  twentyeight: require("./images/28.jpg").default,
  twentynine: require("./images/29.jpg").default,
  thirty: require("./images/30.jpg").default,
  thirtyone: require("./images/31.jpg").default,
  thirtytwo: require("./images/32.jpg").default,
  thirtythree: require("./images/33.jpg").default,
  thirtyfour: require("./images/34.jpg").default,
  thirtyfive: require("./images/35.jpg").default,
  thirtysix: require("./images/36.jpg").default,
  thirtyseven: require("./images/37.jpg").default,
  thirtyeight: require("./images/38.jpg").default,
  thirtynine: require("./images/39.jpg").default,
  forty: require("./images/40.jpg").default,
};

export default images;
